# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1my68TKBr0-g7nNCT7dUW51Ex06e2boIm
"""

def my_rec_max(list1):
  if not list1:
    return
  if len(list1) == 1:
    return list1[0]
  if list1[0] > my_rec_max(list1[1:]):
    return list1[0]
  else:
    return my_rec_max(list1[1:])
print(my_rec_max([1, 3, 5, 9]))